FROM python:3.10-slim

RUN apt-get update && apt-get install -y git libgl1 wget

WORKDIR /app

RUN pip install --upgrade pip
RUN pip install accelerate huggingface_hub[hf_xet]
RUN pip install onnxruntime onnx diffusers transformers Pillow fastapi uvicorn
RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

COPY run_sd.py .

CMD ["uvicorn", "run_sd:app", "--host", "0.0.0.0", "--port", "5000"]
